name: Trigger auto deployment for apitaskly

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/apitaskly-AutoDeployTrigger-8854fedd-9256-4104-927a-7a75e8861055.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.APITASKLY_AZURE_CREDENTIALS }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.APITASKLY_REGISTRY_USERNAME }}
          password: ${{ secrets.APITASKLY_REGISTRY_PASSWORD }}
      - name: Build and push Docker images
        run: |
          docker-compose -f docker-compose.yaml build web
          docker-compose -f docker-compose.yaml push web
          docker-compose -f docker-compose.yaml build sql_server
          docker-compose -f docker-compose.yaml push sql_server
        env:
          COMPOSE_PROJECT_NAME: apitaskly
      - name: Update Azure Container Instance
        run: |
          az container create --resource-group apiTaskL_group --name apitaskly --image ${{ secrets.APITASKLY_REGISTRY_USERNAME }}/apitaskly:${{ github.sha }} --dns-name-label apitaskly --ports 80
      - name: Update Azure Container Instance for web service
        run: |
          az container create --resource-group apiTaskL_group --name apitaskly-web --image ${{ secrets.APITASKLY_REGISTRY_USERNAME }}/apitaskly-web:${{ github.sha }} --dns-name-label apitaskly-web --ports 80

      - name: Update Azure Container Instance for sql_server service
        run: |
          az container create --resource-group apiTaskL_group --name apitaskly-sql_server --image ${{ secrets.APITASKLY_REGISTRY_USERNAME }}/apitaskly-sql_server:${{ github.sha }} --dns-name-label apitaskly-sql_server --ports 1433
